In [1]:
# Exercise 1: 
# Create the following arrays:
# 1. A 1D array of numbers from 0 to 9
import numpy as np

data=np.arange(0,10)
print(data)

# 2. A 2D array of shape (3, 4) filled with zeros

data=np.zeros((3,4), dtype=int)
print(data)

# 3. A 3x3 identity matrix

identity = np.eye(3 ,dtype=int)
print(identity)

# 4. A 1D array of 10 equally spaced values between 1 and 100

linespace_arr = np.linspace(1,100,10)
print(f"{linespace_arr}")

# 5. A 3x3 array with random integers between 10 and 50

data = np.random.randint(10, 51, size=(3, 3))
print(data)

# Print all arrays



[0 1 2 3 4 5 6 7 8 9]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[[38 17 46]
 [38 46 32]
 [40 32 48]]


In [5]:
# Exercise 2: 
# Create a 3D array with shape (2, 3, 4) using random numbers
# Find and print:
# - Number of dimensions
# - Shape of the array
# - Total number of elements
# - Data type of elements
# - Size in bytes of each element
# - Total memory consumed by the array

import numpy as np

import numpy as np

# Create a 3D array with shape (2, 3, 4)
arr = np.random.randint(1,100,size=(2, 3, 4))

# Required properties
print("Array:\n", arr)
print("Number of dimensions:", arr.ndim)
print("Shape of the array:", arr.shape)
print("Total number of elements:", arr.size)
print("Data type of elements:", arr.dtype)
print("Size in bytes of each element:", arr.itemsize)
print("Total memory consumed (bytes):", arr.nbytes)







Array:
 [[[52 88 12 82]
  [16 31 49  1]
  [98 44 14 37]]

 [[72 77 33 42]
  [21 71 91 54]
  [37  3  2 95]]]
Number of dimensions: 3
Shape of the array: (2, 3, 4)
Total number of elements: 24
Data type of elements: int32
Size in bytes of each element: 4
Total memory consumed (bytes): 96


In [11]:
# Exercise 3: 
# Create a 1D array of numbers from 1 to 20
# Perform the following operations:
# - Access the first, last, and middle elements
# - Slice the array to get elements from index 5 to 15
# - Get all even numbers using slicing
# - Reverse the array using slicing

arr=np.arange(1,20)
print(arr)
# - Access the first, last, and middle elements
print(f"First :",arr[0])
print(f"Last : ",arr[-1])

# - Slice the array to get elements from index 5 to 15
print(arr[5:16])

# - Get all even numbers using slicing
arr2=arr[arr%2==0]
print(arr2)

# Reverse the array using slicing
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
First : 1
Last :  19
[ 6  7  8  9 10 11 12 13 14 15 16]
[ 2  4  6  8 10 12 14 16 18]
Reversed array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [17]:
# Exercise 4: 
# Create a 5x5 array with numbers from 1 to 25
# Perform the following tasks:
# - Access the element at row 2, column 3
# - Extract the third row and second column
# - Slice a 3x3 sub-matrix from the center
# - Replace all values in the last row with 0
# - Change the first column to all -1

arr=np.random.randint(1,26,size=(5,5))
print(arr)

# - Access the element at row 2, column 3
print(arr[2,3])

# - Extract the third row and second column
num=arr[3,2]
print(num)

# - Slice a 3x3 sub-matrix from the center
print(arr[1:4,1:4])

# - Replace all values in the last row with 0
arr[4:]=0
print(arr[4:])

# - Change the first column to all -1

arr[0:5,0:1]=-1
print(arr[0:5,0:1])






[[ 6  3 16 14 24]
 [ 3  8  1 18 17]
 [ 3 24 11  8 23]
 [15 11  1 23 18]
 [14 13  2 22  4]]
8
1
[[ 8  1 18]
 [24 11  8]
 [11  1 23]]
[[0 0 0 0 0]]
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]]


In [ ]:
# Exercise 5: 
# Create a 1D array of 15 random integers between 1 and 50
# Perform the following:
# - Select elements at indices [1, 3, 5, 7]
# - Find all elements greater than 25
# - Replace all values less than 10 with 10
# - Count how many values are between 20 and 40 (inclusive)
# - Extract only the odd numbers from the array

import numpy as np

# Create a 1D array of 15 random integers between 1 and 50
arr = np.random.randint(1, 50, size=15)
print("Array:", arr)

# 1️⃣ Select elements at indices [1, 3, 5, 7]
selected = arr[[1, 3, 5, 7]]
print("Selected elements:", selected)

# 2️⃣ Find all elements greater than 25
greater_25 = arr[arr > 25]
print("Elements > 25:", greater_25)

# 3️⃣ Replace all values less than 10 with 10
arr[arr < 10] = 10
print("After replacing values < 10:", arr)

# 4️⃣ Count values between 20 and 40 (inclusive)
count = np.sum((arr >= 20) & (arr <= 40))
print("Count between 20 and 40:", count)

# 5️⃣ Extract only odd numbers
odd_numbers = arr[arr % 2 != 0]
print("Odd numbers:", odd_numbers)
